### ISSUE TITLE
Cant connect, Windows Android Emulator

### ISSUE THREAD

**Issue by LarsKrogJensen** [blankapp/flutter-debugger#2]
Tool looks really useful, however I cannot make any plugins show up when running on Windows with the stock Android Emulator. Followed the getting started guide.

The example app repo was empty so I cannot verify if it is in my app or something else.

The console (Flipper) output, not sure it is relevant:
![image](https://user-images.githubusercontent.com/10598589/57030832-4f922880-6c46-11e9-833d-2b36ffc7dfd0.png)

Thanks for this tool.

**Comment by lijy91** [comment]
Flipper not officially support windows

**Comment by lijy91** [comment]
@LarsKrogJensen flipper has provided windows version. https://fbflipper.com/
